feat/16 Add request handlers for "/", "webhook", and "commit/?id=<commithashid>"
DD2480-Group17/assignment2 pull request #42
Opened 2020-02-04 20:45 UTC by georgewbar

ContinousIntegration class was modified to have three inner subclasses
of GeneralRequestHandler (which is a subclass AbstractRequestHandler).
Each subclass is created to handle requests of different types.

* WebhookRequestHandler handles request with path "/webhook/", which is used by
POST requests of github webhooks.
* CommitHashRequestHandler handles get requests with path "/commit?id=<commit hash id>",
where <commit hash id> is replaced with a commit hash id.
* ListHistoryRequestHandler handles get requests with path "/",
which is used to list the push history.

`//TODO` rows were added in the places of the methods that need to edited
to call methods that general the actual HTML responses.

2020-02-04 20:50 UTC, georgewbar commented
@johannaii now, you can edit the places with the `//TODO` rows to call your functions.

2020-02-05 12:13 UTC, EdvinArdo requested changes
Looks good. Some code duplications, but no big deal. One instance of wrong documentation.

2020-02-05 12:13 UTC, EdvinArdo commented on src/main/java/ContinousIntegrationServer.java
> +         * Returns an HTML formatted string as a response, to handle a request with path "/webhook".
Does not return a HTML formatted string

2020-02-05 12:36 UTC, EdvinArdo approved these changes
Looks good

2020-02-05 12:38 UTC, merged